### ISSUE TITLE
The provided pre-training model could not be loaded

### ISSUE THREAD

**Issue by sorrowyn** [ReML-AI/MGTN#1]
`RuntimeError: Error(s) in loading state_dict for DataParallel:
Missing key(s) in state_dict: "module.mods", "module.backbone0.0.weight", "module.backbone0.1.weight", "module.backbone0.1.bias", "module.backbone0.1.running_mean", "module.backbone0.1.running_var", "module.backbone0.4.0.conv1.weight", "module.backbone0.4.0.bn1.we`

**Comment by sonvx** [comment]
It seems you load the checkpoint without DataParallel, you can do it manually:

```
        state_dict =checkpoint['state_dict']
        from collections import OrderedDict
        new_state_dict = OrderedDict()

        for k, v in state_dict.items():
            if 'module' not in k:
                k = 'module.'+k
            else:
                k = k.replace('features.module.', 'module.features.')
            new_state_dict[k]=v

        model.load_state_dict(new_state_dict)
```

**Comment by sorrowyn** [comment]
> 
> 
> It seems you load the checkpoint without DataParallel, you can do it manually:
> 
> ```
>         state_dict =checkpoint['state_dict']
>         from collections import OrderedDict
>         new_state_dict = OrderedDict()
> 
>         for k, v in state_dict.items():
>             if 'module' not in k:
>                 k = 'module.'+k
>             else:
>                 k = k.replace('features.module.', 'module.features.')
>             new_state_dict[k]=v
> 
>         model.load_state_dict(new_state_dict)
> ```
Thanks for elder.
in models.py file, we still need to fix it.
`            self.add_module('resnet' + str(i+1), backbone)
            self.backbones.append(backbone)
            pooling = nn.MaxPool2d(14, 14)
            self.add_module('pooling' + str(i+1), pooling)
            self.poolings.append(pooling)`

**Comment by sorrowyn** [comment]
`        if self.state['use_gpu']:
            train_loader.pin_memory = True
            val_loader.pin_memory = True
            cudnn.benchmark = False
            model = torch.nn.DataParallel(model, device_ids=self.state['device_ids']).cuda()
            # model = model.cuda()

            criterion = criterion.cuda()

        # optionally resume from a checkpoint
        if self._state('resume') is not None:
            print("******************")
            if os.path.isfile(self.state['resume']):
                print("=> loading checkpoint '{}'".format(self.state['resume']))
                checkpoint = torch.load(self.state['resume'])
                self.state['start_epoch'] = checkpoint['epoch']
                self.state['best_score'] = checkpoint['best_score']
                state_dict =checkpoint['state_dict']
                from collections import OrderedDict
                new_state_dict = OrderedDict()

                for k, v in state_dict.items():
                    if 'module' not in k:
                        k = 'module.'+k
                    else:
                        k = k.replace('features.module.', 'module.features.')

                model.load_state_dict(new_state_dict)
                print("=> loaded checkpoint '{}' (epoch {})"
                      .format(self.state['evaluate'], checkpoint['epoch']))
            else:
                print("=> no checkpoint found at '{}'".format(self.state['resume']))`
